apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  APP_SECRET_DATASOURCE_USERNAME: {{ .Values.app.auth.postgres.username }}
  APP_SECRET_DATASOURCE_PASSWORD: {{ .Values.app.auth.postgres.password }}
