apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app
  labels:
    app.kubernetes.io/name: auth
spec:
  selector:
    app.kubernetes.io/name: auth
  ports:
    - port: 8000
      targetPort: port