#
#The job inserts initial data into the Postgres DB.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: profile-initdb-job
  labels:
    app.kubernetes.io/name: profile
spec:
  template:
    spec:
      containers:
        - name: profile-initdb-container
          image: postgres:15.3
          command: ["bash"]
          # wait 20 seconds to make sure that postgres is ready. The solution is bad but simple.
          args: ["-c", "sleep 20 && \
                        PGPASSWORD={{ .Values.app.postgres.password }} \
                        psql -w -a \
                             -h {{ .Values.app.postgres.host }} \
                             -p {{ .Values.app.postgres.port }} \
                             -U {{ .Values.app.postgres.username }} \
                             -d {{ .Values.app.postgres.database }} \
                             -f /init-db/init-db.sql"]
          volumeMounts:
            - name: profile-initdb-volume
              mountPath: /init-db
      volumes:
        - name: profile-initdb-volume
          configMap:
            name: profile-initdb-configmap
      restartPolicy: OnFailure
  backoffLimit: 3
