apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app.kubernetes.io/name: profile
spec:
  selector:
    app.kubernetes.io/name: profile
  ports:
    - port: 8000
      targetPort: port