apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
  namespace: app
type: Opaque
stringData:
  APP_SECRET_DATASOURCE_USERNAME: {{ .Values.profile.postgres.username }}
  APP_SECRET_DATASOURCE_PASSWORD: {{ .Values.profile.postgres.password }}
