#
#The job inserts initial data into the Postgres DB.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: profile-initdb-job
  namespace: app
  labels:
    app.kubernetes.io/name: profile
spec:
  template:
    spec:
      containers:
        - name: profile-initdb-container
          image: postgres:15.3
          command: ["bash"]
          args: ["-c", "PGPASSWORD={{ .Values.postgres.password }} \
                        psql -w -a \
                             -h {{ .Values.postgres.host }} \
                             -p {{ .Values.postgres.port }} \
                             -U {{ .Values.postgres.username }} \
                             -d {{ .Values.postgres.database }} \
                             -f /init-db/init-db.sql"]
          volumeMounts:
            - name: profile-initdb-volume
              mountPath: /init-db
      volumes:
        - name: profile-initdb-volume
          configMap:
            name: profile-initdb-configmap
      restartPolicy: Never
  backoffLimit: 0
