apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
type: Opaque
stringData:
  APP_SECRET_DATASOURCE_USERNAME: {{ .Values.app.profile.postgres.username }}
  APP_SECRET_DATASOURCE_PASSWORD: {{ .Values.app.profile.postgres.password }}
