apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  application.yml: |
    server:
      port: "8000"
    spring:
      application:
        name: "hw-04"
      datasource:
        url: "jdbc:postgresql://{{ .Values.app.postgres.host }}:{{ .Values.app.postgres.port }}/{{ .Values.app.postgres.database }}"
