apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  APP_SECRET_DATASOURCE_USERNAME: {{ .Values.app.postgres.username }}
  APP_SECRET_DATASOURCE_PASSWORD: {{ .Values.app.postgres.password }}
