apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app.kubernetes.io/name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
    spec:
      containers:
        - name: order-container
          env:
            - name: DB_URL
              value: jdbc:postgresql://{{ .Values.app.postgres.host }}:{{ .Values.app.postgres.port }}/{{ .Values.app.postgres.database }}?currentSchema=order_service
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: APP_SECRET_DATASOURCE_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: APP_SECRET_DATASOURCE_PASSWORD
          image: id1234ht8/order-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: port
