apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app.kubernetes.io/name: order
spec:
  selector:
    app.kubernetes.io/name: order
  ports:
    - port: 8000
      targetPort: port
