apiVersion: v1
kind: ConfigMap
metadata:
  name: app-initdb-configmap
data:
  init-db.sql: |
    CREATE TABLE IF NOT EXISTS users(id INT PRIMARY KEY, username VARCHAR(256), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), phone VARCHAR(15));
    CREATE SEQUENCE IF NOT EXISTS users_seq AS BIGINT INCREMENT 50;
