apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app.kubernetes.io/name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      containers:
        - name: auth-container
          env:
            - name: DB_URL
              value: jdbc:postgresql://{{ .Values.app.postgres.host }}:{{ .Values.app.postgres.port }}/{{ .Values.app.postgres.database }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: APP_SECRET_DATASOURCE_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: APP_SECRET_DATASOURCE_PASSWORD
          image: id1234ht8/auth-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: port
