apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app.kubernetes.io/name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: profile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profile
    spec:
      containers:
        - name: profile-container
          env:
            - name: DB_URL
              value: jdbc:postgresql://{{ .Values.app.postgres.host }}:{{ .Values.app.postgres.port }}/{{ .Values.app.postgres.database }}?currentSchema=profile_service
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: APP_SECRET_DATASOURCE_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-secret
                  key: APP_SECRET_DATASOURCE_PASSWORD
          image: id1234ht8/profile-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: port
